name: mycampus
description: MyCampus Flutter app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.13.0
  flutter: ^3.47.0

dependencies:
  bloc: ^9.2.1
  easy_localization: ^3.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  go_router: ^15.1.2
  intl: ^0.20.2
  shared_preferences: ^2.5.3

dev_dependencies:
  bloc_lint: ^0.4.2
  bloc_test: ^10.0.0
  bloc_tools: ^0.1.0-dev.24
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.5
  very_good_analysis: ^11.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_logo.png"
